-- AlterTable
ALTER TABLE "Blog" ALTER COLUMN "dislike" DROP DEFAULT,
ALTER COLUMN "likes" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "bio" DROP DEFAULT,
ALTER COLUMN "city" DROP DEFAULT;
